version: '3.6'
services:
  swoole:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8099:8099"
    volumes:
      - .:/var/www
    tty: true
    stdin_open: true
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
volumes:
    dynamodb:
        driver: local